---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: orchestrators.orchestrator.parodos.dev
spec:
  group: orchestrator.parodos.dev
  names:
    kind: Orchestrator
    listKind: OrchestratorList
    plural: orchestrators
    singular: orchestrator
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[-1:].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[-1:].reason
      name: Reason
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Orchestrator is the Schema for the orchestrators API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Orchestrator
            type: object
            properties:
              argocd:
                description: ArgoCD contains the fields for the ArgoCD configuration
                type: object
                properties:
                  enabled:
                    description: Enabled determines whether to install the ArgoCD plugin and create the orchestrator AppProject
                    type: boolean
                    default: false
                  namespace:
                    description: Namespace defines the namespace where ther ArgoCD operator is deployed and is watching for argoapp CR instances
                    type: string
                    default: orchestrator-gitops
                  password:
                    description: Password contains the password to use to authenticate with the ArgoCD instance
                    type: string
                  url:
                    description: URL contains the REST API endpoint of the ArgoCD instance
                    type: string
                  username:
                    description: Username contains the username to authenticate against the ArgoCD instance
                    type: string
                    default: admin
              orchestrator:
                description: Orchestrator contains the fields for the orchestrator configuration
                type: object
                properties:
                  namespace:
                    description: Namespace where the data index, job service and workflows are deployed
                    type: string
                    default: sonataflow-infra
                  sonataPlatform:
                    description: SonataflowPlatform contains the pod resource configuration to be used for the data index and job services
                    type: object
                    properties:
                      resources:
                        description: Resources contains the requests and limit of CPU and memory resources for the pod instance
                        type: object
                        properties:
                          limits:
                            description: 'Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                            type: object
                            properties:
                              cpu:
                                description: CPU defines the CPU resource limits
                                type: string
                                default: 500m
                              memory:
                                description: Memory defines the memory resource limits
                                type: string
                                default: 1Gi
                          requests:
                            description: |
                              Requests describes the minimum amount of compute resources required. If Requests is omitted for a container,
                              it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value.
                              Requests cannot exceed Limits. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
                            type: object
                            properties:
                              cpu:
                                description: CPU defines the CPU resource limits
                                type: string
                                default: 250m
                              memory:
                                description: Memory defines the memory resource limits
                                type: string
                                default: 64Mi
              postgres:
                description: Postgres contains the configuration to be injected in the SonataflowPlatform configuration to setup the persistency in the sonataflows
                type: object
                properties:
                  authSecret:
                    description: name of existing secret to use for PostgreSQL credentials.
                    type: object
                    properties:
                      name:
                        description: name of existing secret to use for PostgreSQL credentials.
                        type: string
                        default: sonataflow-psql-postgresql
                      passwordKey:
                        description: name of key in existing secret to use for PostgreSQL credentials
                        type: string
                        default:
                      userKey:
                        description: name of key in existing secret to use for PostgreSQL credentials.
                        type: string
                        default: postgres-username
                  database:
                    description: Database describes the name of the existing database instance used by data index and job service. Defaults to sonataflow
                    type: string
                    default: sonataflow
                  serviceName:
                    description: ServiceName specifies the kubernetes service that exposes the PostgreSQL service. Defaults to sonataflow-psql-postgresql
                    type: string
                    default: sonataflow-psql-postgresql
                  serviceNamespace:
                    description: ServiceNamespace specifies the kubernetes namespace where the PostgreSQL service is located. Defaults to sonataflow-infra
                    type: string
                    default: sonataflow-infra
              rhdhOperator:
                description:
                type: object
                properties:
                  enabled:
                    description: Enabled determines whether the operator should be deployed by the chart. Defaults to true
                    type: boolean
                    default: true
                  github:
                    description: Github contains the configuration parameters to connect to the GitHub server.
                    type: object
                    properties:
                      clientId:
                        description: ClientID defines the client ID that you generated on GitHub, for GitHub authentication (requires GitHub App).
                        type: string
                      clientSecret:
                        description: ClientSecret defines the client secret tied to the generated client ID.
                        type: string
                      token:
                        description: Token defines the authentication token as expected by GitHub. Required for importing resource to the catalog, launching software templates and more.
                        type: string
                  k8s:
                    description: K8s contains the kubernetes configuration properties used to connect with the KAPI server
                    type: object
                    properties:
                      clusterToken:
                        description: ClusterToken contains the kubernetes API bearer token used for authentication.
                        type: string
                      clusterUrl:
                        description: ClusterURL contains the API URL of the kubernetes cluster
                        type: string
                  subscription:
                    description: Subscription specifies the subscription attributes to use to deploy the operator.
                    type: object
                    properties:
                      channel:
                        description: Channel defines the channel of the operator package to subscribe to
                        type: string
                        default: fast
                      installPlanApproval:
                        description: InstallPlanApproval specifies the approval policy for an InstallPlan. It must be one of "Automatic" or "Manual". Defaults to Automatic.
                        type: string
                        default: Automatic
                      name:
                        description: Name defines the name of the operator package
                        type: string
                        default: rhdh
                      namespace:
                        description: Namespace determines the namespace where the operator should be deployed. Defaults to rhdh-operator
                        type: string
                        default:  rhdh-operator
                serverlessOperator:
                  description:
                  type: object
                  properties:
                    enabled:
                      description: Enabled determines whether the operator should be deployed by the chart. Defaults to true.
                      type: boolean
                      default: true
                    subscription:
                      description: Subscription specifies the subscription attributes to use to deploy the operator.
                      type: object
                      properties:
                        channel:
                          description: Channel defines the channel of the operator package to subscribe to
                          type: string
                          default: stable
                        installPlanApproval:
                          description: InstallPlanApproval specifies the approval policy for an InstallPlan. It must be one of "Automatic" or "Manual". Defaults to Automatic.
                          type: string
                          default: Automatic
                        name:
                          description: Name defines the name of the operator package
                          type: string
                          default: serverless-operator
                        namespace:
                          description: Namespace determines the namespace where the operator should be deployed. Defaults to openshift-serverless
                          type: string
                          default: openshift-serverless
              sonataFlowOperator:
                description: SonatafFlowOperator contains the configuration fields for the SonataFlow Operator
                type: object
                properties:
                  enabled:
                    description: Enabled determines whether to deploy the SonataFlow Operator operator or not. Defaults to true.
                    type: boolean
                    default: true
                    subscription:
                      description: Subscription specifies the subscription attributes to use to deploy the operator.
                      type: object
                      properties:
                        channel:
                          description: Channel defines the channel of the operator package to subscribe to
                          type: string
                          default: alpha
                        installPlanApproval:
                          description: InstallPlanApproval specifies the approval policy for an InstallPlan. It must be one of "Automatic" or "Manual". Defaults to Automatic.
                          type: string
                          default: Automatic
                        name:
                          description: Name defines the name of the operator package
                          type: string
                          default: logic-operator-rhel8
                        namespace:
                          description: Namespace determines the namespace where the operator should be deployed. Defaults to openshift-serverless-logic
                          type: string
                          default: openshift-serverless-logic
                tekton:
                  description: Contains the tekton configuration fields
                  type: object
                  properties:
                    enabled:
                      description: Enabled determines whether to create the Tekton pipeline resources. Defaults to false.
                      type: boolean
                      default: false
          status:
            description: Status defines the observed state of Orchestrator
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
